stages:
  - check

default:
  image: ansible/ansible-runner:latest

syntax-check:
  stage: check
  script:
    - ansible-playbook deploy.yml --syntax-check -e target=localhost
  only:
    refs:
      - develop
      - master
      - /^feature.*$/
  when: manual
